go
alter table ReportesPorLinea add  ComandoDetalle varchar(500) null
go
alter table ReportesPorLinea add  TotalDecimales smallint  

go

/*Insercion de lineas de reporte 170*/
IF NOT EXISTS(SELECT * FROM ReportesPorLinea where Reporte = 170)
BEGIN
SET IDENTITY_INSERT [dbo].[ReportesPorLinea] ON
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (424, 170, N'', N'Total de ingresos acumulables', N'', 0, 0, 1, 1, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (425, 170, N'-', N'Total de deducciones autorizadas', N'', 0, 0, 1, 2, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (426, 170, N'=', N'Utilidad o pérdida fiscal antes de PTU', N'', 1, 0, 1, 3, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (427, 170, N'-', N'PTU pagada en el ejercicio', N'', 0, 0, 1, 4, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (428, 170, N'=', N'Utilidad fiscal del ejercicio', N'', 1, 0, 1, 5, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (429, 170, N'=', N'Pérdida fiscal del ejercicio', N'', 1, 0, 1, 6, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (430, 170, N'-', N'Pérdidas fiscales de ejercicios anteriores que se aplican en el ejercicio', N'', 0, 0, 1, 7, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (431, 170, N'=', N'Resultado fiscal', N'', 1, 0, 1, 8, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (432, 170, N'X', N'Porcentaje del ISR', N'', 0, 0, 1, 9, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (433, 170, N'=', N'Impuesto Sobre la Renta del ejercicio', N'', 1, 0, 1, 10, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (434, 170, N'-', N'Reducciones para maquiladoras', N'', 0, 0, 1, 11, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (435, 170, N'-', N'Crédito fiscal por deducción inmediata para maquiladoras', N'', 0, 0, 1, 12, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (436, 170, N'-', N'Otras reducciones de ISR', N'', 0, 0, 1, 13, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (437, 170, N'=', N'Impuesto causado en el ejercicio', N'', 1, 0, 1, 14, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (438, 170, N'-', N'Estímulo por proyectos en investigación y desarrollo tecnológico realizados en el ejercicio', N'', 0, 1, 1, 15, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (439, 170, N'-', N'Estímulo por proyectos de inversión en la producción cinematográfica nacional', N'', 0, 0, 1, 16, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (440, 170, N'-', N'Otros estímulos', N'', 0, 1, 1, 17, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (441, 170, N'=', N'Total de estímulos', N'', 1, 0, 1, 18, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (442, 170, N'-', N'Pagos provisionales efectuados entregados a la controladora', N'', 0, 0, 1, 19, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (443, 170, N'-', N'Pagos provisionales efectuados entregados a la federación', N'', 0, 0, 1, 20, 1, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (444, 170, N'-', N'Impuesto retenido al contribuyente', N'', 0, 0, 1, 21, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (445, 170, N'-', N'Impuesto acreditable pagado en el extranjero', N'', 0, 1, 1, 22, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (446, 170, N'-', N'Impuesto acreditable por dividendos o utilidades distribuidos', N'', 0, 1, 1, 23, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (447, 170, N'-', N'Crédito fiscal IETU por deducciones mayores a los ingresos (base negativa)', N'', 0, 0, 1, 24, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (448, 170, N'-   ', N'Impuesto correspondiente a la consolidación fiscal a cargo', N'                                                                                                                                                                                                        ', 0, 1, 1, 25, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (449, 170, N'-', N'Impuesto correspondiente a la consolidación fiscal entregado (en exceso) ', N'', 0, 1, 1, 26, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (450, 170, N'-', N'Impuesto por inversiones en territorios con regímenes fiscales preferentes', N'', 0, 1, 1, 27, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (451, 170, N'-', N'Impuestos sobre ingresos sujetos a regímenes fiscales preferentes', N'', 0, 1, 1, 28, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (452, 170, N'=', N'Diferencia a cargo', N'', 1, 0, 1, 29, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (453, 170, N'=', N'Diferencia a favor', N'', 1, 0, 1, 30, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (454, 170, N'-', N'Impuesto acreditable por depósitos en efectivo (IDE)', N'', 0, 0, 1, 31, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (455, 170, N'-', N'Impuesto a la venta de bienes y servicios suntuarios acreditable', N'', 0, 1, 1, 32, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (456, 170, N'-   ', N'ISR pagado en exceso aplicado contra el IMAPC', N'                                                                                                                                                                                                        ', 0, 0, 1, 33, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (457, 170, N'=', N'Impuesto a cargo del ejercicio', N'', 2, 0, 1, 34, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (458, 170, N'=   ', N'Saldo a favor del ejercicio', N'                                                                                                                                                                                                        ', 2, 0, 1, 35, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (459, 170, N'', N'Monto aplicado del IDE (a favor) contra retenciones', N'', 0, 0, 1, 36, 0, 0, 0, 1, NULL, N'', 2)
INSERT [dbo].[ReportesPorLinea] ([IdRepLinea], [Reporte], [Signo], [Texto], [Formula], [Funcion], [EsCaptura], [Columna], [Linea], [TieneDetalle], [EsMovtos], [EsTasa], [Seccion], [CondicionVisible], [ComandoDetalle], [TotalDecimales]) VALUES (460, 170, N'', N'Diferencia por aplicar de IDE', N'', 0, 0, 1, 37, 0, 0, 0, 1, NULL, N'', 2)
SET IDENTITY_INSERT [dbo].[ReportesPorLinea] OFF
END